version: "2.12.2"
services: 
  client: 
    # depends_on:
    #   - reverse-proxy
    container_name: client
    image: xword-client
    build:
      context: ./
      dockerfile: ./docker/apps/client/Dockerfile
    ports:
      - "8080:80"
    # expose:
    #   - "80"
    restart: always
  server: 
    # depends_on:
    #   - reverse-proxy
    container_name: server
    image: xword-server
    build:
      context: ./
      dockerfile: ./docker/apps/server/Dockerfile
    # ports:
    #   - "4444:4444"
    expose:
      - "4444"
      - "3333"
    restart: always
  # reverse-proxy:
  #   image: reverse-proxy
  #   build:
  #     context: ./
  #     dockerfile: ./docker/reverse-proxy/Dockerfile
  #   ports: 
  #     - "8080:8080"
  #     - "4444:4444"
  #     # - "3333:3333"
  #   restart: always
    
# GCP VM deploy commands in ~kyss/nx
# 
# git pull
# npm i
# npx nx run client:build:production
# npx nx run server:build:production

# kill running docker containers
# sudo docker system prune


# sudo docker compose build --no-cache
# sudo docker network create xword
# sudo docker run -d --name server --network xword --env-file ./apps/server/.env xword-server 
# sudo docker run -dp 8080:80 --network xword xword-client

# sudo systemctl restart nginx
  
  
 